---
# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Prepare distros matrix
jobs:

# Prepare distros matrix
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      distrobox_changed: ${{ steps.check_file_changed.outputs.distrobox_changed }}
    steps:

      - uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      # Fetch from compatibility table all the distros supported
      - id: check_file_changed
        run: |
          if git diff --name-only HEAD^ HEAD  | grep -E "^docs|gen-man"; then
            echo "::set-output name=distrobox_changed::True"
          else
            echo "::set-output name=distrobox_changed::False"
          fi

  gen_man:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.distrobox_changed == 'True'
    steps:

      - uses: actions/checkout@v2

      # Fetch from compatibility table all the distros supported
      - id: generate
        run: |
          RELEASE=$(curl -L https://github.com/jgm/pandoc/releases/latest | grep href | grep pandoc | grep download | grep deb | grep amd64 | tail -1 | cut -d'"' -f2)
          NAME=$(echo $RELEASE | rev | cut -d'/' -f1 | rev)

          curl -L https://github.com/$RELEASE -o $NAME
          sudo apt-get install -y ./$NAME
          sudo apt-get install -y ronn

          rm -f $NAME

          man/gen-man

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Automatic Man Page Update
          commit_options: '--no-verify --signoff'
          commit_user_name: distrobox-docs-bot
          commit_user_email: distrobox-docs-bot@users.noreply.github.com
          commit_author: distrobox-docs-bot <actions@github.com>
